// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZB1bTbu36Q_SfqZx6rhWvPbDen7NPIeA',
    appId: '1:283944913136:web:7c792940829765fdfb5a35',
    messagingSenderId: '283944913136',
    projectId: 'phone-auth-1da4f',
    authDomain: 'phone-auth-1da4f.firebaseapp.com',
    storageBucket: 'phone-auth-1da4f.firebasestorage.app',
    measurementId: 'G-M5QFN609R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNr9n-dfyor_nJGQrKs3AGA6Twba_0rkc',
    appId: '1:283944913136:android:01af18e38b5b8076fb5a35',
    messagingSenderId: '283944913136',
    projectId: 'phone-auth-1da4f',
    storageBucket: 'phone-auth-1da4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqZuEgODge6wpPsn3F2UO8kbbNlhtmkmA',
    appId: '1:283944913136:ios:32918e7894a37e8dfb5a35',
    messagingSenderId: '283944913136',
    projectId: 'phone-auth-1da4f',
    storageBucket: 'phone-auth-1da4f.firebasestorage.app',
    iosBundleId: 'com.example.phoneAuthFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqZuEgODge6wpPsn3F2UO8kbbNlhtmkmA',
    appId: '1:283944913136:ios:32918e7894a37e8dfb5a35',
    messagingSenderId: '283944913136',
    projectId: 'phone-auth-1da4f',
    storageBucket: 'phone-auth-1da4f.firebasestorage.app',
    iosBundleId: 'com.example.phoneAuthFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZB1bTbu36Q_SfqZx6rhWvPbDen7NPIeA',
    appId: '1:283944913136:web:1aba57aac9406903fb5a35',
    messagingSenderId: '283944913136',
    projectId: 'phone-auth-1da4f',
    authDomain: 'phone-auth-1da4f.firebaseapp.com',
    storageBucket: 'phone-auth-1da4f.firebasestorage.app',
    measurementId: 'G-MXRRM7PD8N',
  );
}
